apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf

data:
  nginx.conf: |
    events {}
    http {
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_ciphers 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256';
      ssl_prefer_server_ciphers on;
      client_body_timeout 10s;
      client_header_timeout 10s;
      keepalive_timeout 60s;
      send_timeout 10s;
      proxy_connect_timeout 10s;
      proxy_read_timeout 10s;
      allow 31.0.127.101;
      allow 10.200.31.22/24;
      allow 10.200.31.1;
      allow 172.29.112.1;
      allow 192.168.0.25/24;
      allow 192.168.0.25;
      allow 192.168.0.1/24;
      allow 192.168.0.1;
      deny all;

      server {
        listen 6969;
        server_tokens off;
        allow 31.0.127.101;
        allow 10.200.31.22/24;
        allow 10.200.31.1;
        allow 172.29.112.1;
        allow 192.168.0.25/24;
        allow 192.168.0.25;
        allow 192.168.0.1/24;
        allow 192.168.0.1;
        deny all;
        location / {
            allow 31.0.127.101;
            allow 10.200.31.22/24;
            allow 10.200.31.1;
            allow 172.29.112.1;
            allow 192.168.0.25/24;
            allow 192.168.0.1/24;
            allow 192.168.0.25;
            allow 192.168.0.1;
            deny all;
            root /usr/share/nginx/html;
            index index.html;
        }
      }
    }